### ISSUE TITLE
Starter Content Import Doesn't Work

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/rosa2-lite#16]
When I try to import Starter Content, I get [this error](https://pixelgrade.com/docs/timber/guides-and-resources/server-errors-handling/#error_500):

![Screenshot at Mar 09 14-36-52](https://user-images.githubusercontent.com/6790170/76213468-6fee2480-6213-11ea-9ccb-1099ea9f9fc2.png)

It seems that only the Media Library items are imported and nothing else.

**Comment by madalingorbanescu** [comment]
@alinclamba I've just made a fresh installation of Rosa2 Lite and everything was without errors. Can you test one more time and let me know the result?

Thank you.

**Comment by alinclamba** [comment]
You're right, @madalingorbanescu. I've just tested this again and it works just fine.

**Comment by madalingorbanescu** [comment]
Thank you @alinclamba.
