### ISSUE TITLE
Rosa 2 Lite Child Theme

### ISSUE THREAD

**Issue by sppmasterspp** [pixelgrade/rosa2-lite#22]
Can you make a Child theme for the Rosa 2 lite. I cannot find one.

**Comment by madalingorbanescu** [comment]
Hey @sppmasterspp,

You can use the child theme created for Rosa2 which can be downloaded from [here](https://pxg.to/rosa2-child).

You just need to the `style.css` inside child theme, and replace `Template: rosa2` with `Template: rosa2-lite`.

Let me know if that solved your problem.

**Comment by madalingorbanescu** [comment]
I will consider that my previous answer helped you and will close this issue.
