### ISSUE TITLE
Unable to show submenu in navigation

### ISSUE THREAD

**Issue by shiva2415** [pixelgrade/rosa2-lite#46]
I have created a navigation menu with submenu. 
But the submenu is not showing in dropdown.

**Comment by madalingorbanescu** [comment]
Hey @shiva2415,

Unfortunately, the submenu is a feature available only in the[ PRO version of Rosa 2](https://pixelgrade.com/themes/rosa2-pro). In the PRO version, you also get access to more blocks, Header, and Footer Block Areas which you customize for your own needs plus many more features.
