### ISSUE TITLE
Food menu block is not displaying properly on loading

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2-lite#8]
When I'm loading the Food menu there seems to be some extra spacing added to each Menu Item.

The only way to make the issue disappear is by resizing the browser window, but on refresh, the issue shows up again.

Here's proof: https://share.getcloudapp.com/nOumrRox

**Comment by madalingorbanescu** [comment]
The problem has already been solved in https://github.com/pixelgrade/rosa2-lite/issues/7
